### ISSUE TITLE
Talk Proposal: Create a Test Suite with Docker 

### ISSUE THREAD

**Issue by argemiront** [VanJS/meetup#39]
Draft Title: Create a Test Suite with Docker 
Length: 30m Presentation
Links: TBD - just a proposal at the moment
In this talk, we'll discuss how to create a rich, flexible and powerfull test suite for APIs using Docker containers and Jest. It will be presented how to use NoSQL databases to refresh the data for every test execution.

About Me
Name: Argemiro Neto
bio: Argemiro is a Data Engineer at Semios.
Would you like help with your presentation? Feedback would be appreciated.
Social media link(s): linkedin.com/in/argemironeto
Do you agree to the VanJS Code of Conduct? Yes

**Comment by ShMcK** [comment]
In terms of availability, we're booking into the future these days.

We have a talk booked for Feb 13th on the topic of the AWS JavaScript SDK. We're waiting to hear from someone from the AppSync team to see if they'll confirm an AWS doubleheader. If that talk falls through, Feb 13th, otherwise March?

**Comment by ShMcK** [comment]
After talking with @argemiront will close for now.
